// Code generated by MockGen. DO NOT EDIT.
// Source: conn_test.go
//
// Generated by this command:
//
//	mockgen -source=conn_test.go -destination=conn_mocks_test.go -package=ginmwpg
//

// Package ginmwpg is a generated GoMock package.
package ginmwpg

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pg "github.com/Deimvis-go/xpg/pg"
	pgconn0 "github.com/Deimvis-go/xpg/pg/pgconn"
	xoptional "github.com/Deimvis/go-ext/go1.25/xoptional"
	gomock "go.uber.org/mock/gomock"
)

// MockIConn is a mock of IConn interface.
type MockIConn struct {
	ctrl     *gomock.Controller
	recorder *MockIConnMockRecorder
	isgomock struct{}
}

// MockIConnMockRecorder is the mock recorder for MockIConn.
type MockIConnMockRecorder struct {
	mock *MockIConn
}

// NewMockIConn creates a new mock instance.
func NewMockIConn(ctrl *gomock.Controller) *MockIConn {
	mock := &MockIConn{ctrl: ctrl}
	mock.recorder = &MockIConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConn) EXPECT() *MockIConnMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockIConn) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockIConnMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockIConn)(nil).Begin), ctx)
}

// BeginTx mocks base method.
func (m *MockIConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIConnMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIConn)(nil).BeginTx), ctx, txOptions)
}

// CopyFrom mocks base method.
func (m *MockIConn) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockIConnMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockIConn)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockIConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIConnMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIConn)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockIConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockIConnMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockIConn)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockIConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockIConnMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockIConn)(nil).QueryRow), varargs...)
}

// SendBatch mocks base method.
func (m *MockIConn) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockIConnMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockIConn)(nil).SendBatch), ctx, b)
}

// MockOwnedConn is a mock of OwnedConn interface.
type MockOwnedConn struct {
	ctrl     *gomock.Controller
	recorder *MockOwnedConnMockRecorder
	isgomock struct{}
}

// MockOwnedConnMockRecorder is the mock recorder for MockOwnedConn.
type MockOwnedConnMockRecorder struct {
	mock *MockOwnedConn
}

// NewMockOwnedConn creates a new mock instance.
func NewMockOwnedConn(ctrl *gomock.Controller) *MockOwnedConn {
	mock := &MockOwnedConn{ctrl: ctrl}
	mock.recorder = &MockOwnedConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnedConn) EXPECT() *MockOwnedConnMockRecorder {
	return m.recorder
}

// FreeConn mocks base method.
func (m *MockOwnedConn) FreeConn(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeConn", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeConn indicates an expected call of FreeConn.
func (mr *MockOwnedConnMockRecorder) FreeConn(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeConn", reflect.TypeOf((*MockOwnedConn)(nil).FreeConn), arg0)
}

// MockConnOwnership is a mock of ConnOwnership interface.
type MockConnOwnership struct {
	ctrl     *gomock.Controller
	recorder *MockConnOwnershipMockRecorder
	isgomock struct{}
}

// MockConnOwnershipMockRecorder is the mock recorder for MockConnOwnership.
type MockConnOwnershipMockRecorder struct {
	mock *MockConnOwnership
}

// NewMockConnOwnership creates a new mock instance.
func NewMockConnOwnership(ctrl *gomock.Controller) *MockConnOwnership {
	mock := &MockConnOwnership{ctrl: ctrl}
	mock.recorder = &MockConnOwnershipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnOwnership) EXPECT() *MockConnOwnershipMockRecorder {
	return m.recorder
}

// MustTake mocks base method.
func (m *MockConnOwnership) MustTake() pgconn0.OwnedConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustTake")
	ret0, _ := ret[0].(pgconn0.OwnedConn)
	return ret0
}

// MustTake indicates an expected call of MustTake.
func (mr *MockConnOwnershipMockRecorder) MustTake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustTake", reflect.TypeOf((*MockConnOwnership)(nil).MustTake))
}

// Take mocks base method.
func (m *MockConnOwnership) Take() (pgconn0.OwnedConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take")
	ret0, _ := ret[0].(pgconn0.OwnedConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Take indicates an expected call of Take.
func (mr *MockConnOwnershipMockRecorder) Take() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockConnOwnership)(nil).Take))
}

// MockConnProvider is a mock of ConnProvider interface.
type MockConnProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConnProviderMockRecorder
	isgomock struct{}
}

// MockConnProviderMockRecorder is the mock recorder for MockConnProvider.
type MockConnProviderMockRecorder struct {
	mock *MockConnProvider
}

// NewMockConnProvider creates a new mock instance.
func NewMockConnProvider(ctrl *gomock.Controller) *MockConnProvider {
	mock := &MockConnProvider{ctrl: ctrl}
	mock.recorder = &MockConnProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnProvider) EXPECT() *MockConnProviderMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockConnProvider) Acquire(arg0 context.Context, arg1 pgconn0.Mode, arg2 ...pgconn0.AcquireOption) (pg.Conn, xoptional.T[pg.ConnOwnership], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Acquire", varargs...)
	ret0, _ := ret[0].(pg.Conn)
	ret1, _ := ret[1].(xoptional.T[pg.ConnOwnership])
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockConnProviderMockRecorder) Acquire(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockConnProvider)(nil).Acquire), varargs...)
}

// AcquireManaged mocks base method.
func (m *MockConnProvider) AcquireManaged(arg0 context.Context, arg1 pgconn0.Mode, arg2 ...pgconn0.AcquireOption) (pg.Conn, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcquireManaged", varargs...)
	ret0, _ := ret[0].(pg.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireManaged indicates an expected call of AcquireManaged.
func (mr *MockConnProviderMockRecorder) AcquireManaged(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireManaged", reflect.TypeOf((*MockConnProvider)(nil).AcquireManaged), varargs...)
}
